name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prevent-direct-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # only on direct push to main
    steps:
      - name: Fail on direct push to main
        run: |
          echo "Direct pushes to main are not allowed. Please use a Pull Request."
          exit 1

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build --filter ./apps/*

      - name: Test
        run: pnpm test --filter ./apps/*
