name: CI

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Prevent direct push to main
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/main' &&
          github.actor != 'github-actions[bot]'
        run: |
          echo "❌ Direct push to main is not allowed. Use a Pull Request instead."
          exit 1

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint all packages
        run: pnpm turbo run lint --parallel

      - name: Type check
        run: pnpm turbo run check-types --parallel

      - name: Build all
        run: pnpm turbo run build --parallel
