name: Deploy Web (Cloudflare Workers)

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
      - "packages/**"

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci
      - run: npx turbo run build --filter=web...
      - run: npx turbo run deploy --filter=web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
